name: 1a
region: "1"
host: 127.0.0.1
port: 2328
stunPort: 3478
dhKey:
    public: BCaOuJzSzYX/ZZgqV6SJh0D/rq/j1fRR2C7WimExejg=
    private: FGFagAhcT5YHVk5kRs2BftlNDvWQYn0xpr6CuKTZc5o=
portal:
    key: my-testing-relay
    url: http://127.0.0.1:2823
    keepaliveInterval: 5m0s
    syncInterval: 5m0s
